import React from 'react';

import Box from '@mui/material/Box';
import S from '@mui/material/Typography';

export default function Classes () {
    return (
        <Box sx={{mt:3}}>
          <S variant="h5">Classes</S>

          <Box sx={{mt:3}}>
            <pre>{graph.join('\n')}</pre>
          </Box>
        </Box>
    );
}

const graph = [
    '+----------------------+   +------------------------+   +--------------------------+   +-----------------------+   +----------------+',
    '| DataModel : Entity   |   | DataModel : Column     |   | DataModel : Relashonship |   | DataModel : Port      |   | ColumnInstance |',
    '|======================|   |========================|   |==========================|   |=======================|   |================|',
    '|+ pool                |   |+ pool                  |   |+ pool                    |   |+ pool                 |   |+ pool          |',
    '|- _place              |   |- _padding              |   |--------------------------|   |+ geometry             |   |----------------|',
    '|- _padding            |   |- _values               |   |+ checkClassOfFromTo      |   |-----------------------|   |+ build         |',
    '|- _values             |   |------------------------|   |+ injectPortAndTable      |   |- calLinePoints        |   +----------------+',
    '|- _callbacks          |   |- columnsWidth          |   |                          |   |- drawLine             |',
    '|- _Column             |   |- columnHeight          |   |<Data manegement>         |   |- calOneLine           |',
    '|+ port                |   |- columnsContentsHeight |   |+ build                   |   |- calThreeLine         |',
    '|- _values             |   |- columnsHeight         |   +--------------------------+   |- calCircle            |',
    '|- _callbacks          |   |                        |               ^                  |                       |',
    '|+ column              |   |<Data manegement>       |               |                  |<Data manegement>      |',
    '|----------------------|   |+ build                 |               |                  |+ build                |',
    '|<util>                |   +------------------------+               |                  +-----------------------+',
    '|  getCallbak          |               ^                            |                              |',
    '|  callCallbak         |               |                            |                              |',
    '|                      |               |                            |                              |',
    '|<Data manegement>     |               |                            |                              |',
    '|  build               |               |                            |                              |',
    '|                      |               |                            |                              |',
    '|<Sizing>              |               |                            |                              |',
    '|  headerWidth         |               |                            |                              |',
    '|  headerContentsHight |               |                            |                              |',
    '|  headerHight         |               |                            |                              |',
    '|  baseHeight          |               |                            |                              |',
    '+----------------------+               |                            |                              |',
    '          ^                            |                            |                              |',
    '          |                            |                            |                              |',
    '+----------------------+   +------------------------+       +----------------+         +-----------------------+',
    '| Entity               |   | Painter: Column        |       | Relashonship   |         | Port                  |',
    '|======================|   |========================|       |================|         |=======================|',
    '|----------------------|   |------------------------|       |----------------|         |                       |',
    '|<Draw>                |   |- sortColumns           |       |- drawCore      |         |-----------------------|',
    '|- removeGAll          |   |+ draw                  |       |+ draw          |         |<Draw>                 |',
    '|- drawHeader          |   |+ resize                |       |+ removeEdgeAll |         |- drawCardinalityOne   |',
    '|- drawBase            |   +------------------------+       |+ moveEdges     |         |- drawCardinalityThree |',
    '|- removeG             |                                    +----------------+         |- drawCardinality      |',
    '|- drawG               |                                                               |- drawOptionalityOne   |',
    '|- move                |                                                               |- drawOptionalityZero  |',
    '|+ resize              |                                                               |- drawOptionality      |',
    '|+ draw                |                                                               |+ draw                 |',
    '|                      |                                                               +-----------------------+',
    '|<Drag & Drop>         |',
    '|- moveEntityStart     |',
    '|- moveEntity          |',
    '|- moveEntityEnd       |',
    '+----------------------+',
    '',
    '',
    '+-------------------------------+        +-------------------------------------+   +---------------------+',
    '| Rectum                        |    +---| DataManeger                         |   | Pool                |',
    '|===============================|    |   |=====================================|   |=====================|',
    '|+ erdm              DataManeger|<---+   |+ table                        Entity|   |---------------------|',
    '|+ relashonship     Relashonship|        |+ port                           Port|   |+ list2pool          |',
    '|- _table                 Entity|        |+ column_instance      ColumnInstance|   |+ list2poolWithIndex |',
    '|- _values                      |        |+ relashonship           Relashonship|   +---------------------+',
    '|- _callbacks                   |        |-------------------------------------|',
    '|-------------------------------|        |- injectTable2ColumnInstances        |',
    '|- initValues                   |        |- injectColumnInstances2Ports        |',
    '|- initCallbacks                |        |                                     |',
    '|                               |        |<Respons data 2 Graph data>          |',
    '|<Getter>                       |        |- buildEdges                         |',
    '|- entity                       |        |+ buldData                           |',
    '|                               |        |                                     |',
    '|<Draw>                         |        |<Import Data (未実装)>               |',
    '|- drawEdges                    |        |+ import2Data                        |',
    '|- moveEdges                    |        +-------------------------------------+',
    '|- drawEntities                 |',
    '|+ draw                         |',
    '|                               |',
    '|<Data>                         |',
    '|+ data                         |',
    '+-------------------------------+',
    '',
    '',
    '+---------------------------+',
    '| Geometry                  |',
    '|===========================|',
    '|---------------------------|',
    '|<Utilities>                |',
    '|+ deg2rad                  |',
    '|                           |',
    '|<Rect>                     |',
    '|+ getFourSideLines         |',
    '|                           |',
    '|<Rect>                     |',
    '|+ getPortLineFrom          |',
    '|+ getPortLineToPoint       |',
    '|+ getPortLineTo            |',
    '|+ getPortLine              |',
    '|                           |',
    '|<Cross Point of two lines> |',
    '|+ isCorss                  |',
    '|+ getCrossPointCore        |',
    '+---------------------------+',
];
